import Navbar from '@/components/Navbar/Navbar'
import Head from 'next/head';
import Footer from '@/components/Footer/Footer'

const About = () => {
    return ( 
    <>
        <Head>
        <title>Squad | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>

      <Footer/>
    </> 
    );
}
 
export default About;