import Head from "next/head";
import Image from "next/image";
import home from "../assets/home.png";
import bg from "../assets/bg.png";
import { Bentham, Inter, Yellowtail } from "@next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import styles from "@/styles/Home.module.css";
import yelpat from "../../public/yellow_pat/yellow_pat.webp";
import yelpat_l from "../../public/yellow_pat/yellow_pat_2x.webp";
import bluepat from "../../public/blue_pat/blue_pat.webp";
import greenpat from "../../public/green_pat/green_pat.webp";
const inter = Inter({ subsets: ["latin"] });

// async function requestAccount() {
//   if (window.ethereum) {
//     try {
//       const accounts = await window.ethereum.request({
//         method: "eth_requestAccounts",
//       });
//       console.log(accounts);
//     } catch (err) {
//       console.log(err);
//     }
//   }
// }


export default function Home() {
  return (
    <>
      <Head>
        <title>Squad | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar navType={"primary"} />
      <main className={styles.main}>
        <div className={styles.box}>
          <div className={styles.boxText}>
            <h1 className={styles.txtNew}> a new way to own </h1>
            <h1 className={styles.txtAssets} style={{ letterSpacing: "1px" }}>
              ASSETS
            </h1>
            <button className={styles.btnPrimary} >
              Connect Wallet
            </button>
            <h1
              style={{
                fontSize: "0.75rem",
                margin: "0.5rem 0 0 3rem",
                fontFamily: "sans-serif !important",
              }}
            >
              *Min 0.2 matic required
            </h1>
          </div>
          <div className={styles.boxImg}>
            <Image src={yelpat_l} alt="hero" className={styles.logo_hero} />
          </div>
        </div>

        <div
          style={{
            display: "flex",
            gap: "5rem",
            alignItems: "center",
            justifyContent: "center",
            marginTop: "6em",
          }}
        >
          <div className={styles.box2}>
            <Image
              alt="yellow pattern"
              src={yelpat}
              className={styles.logo_img}
            />
            <h1
              className={styles.box2Heading}
              style={{ marginBottom: "140px", marginTop: "-115px" }}
            >
              Self Recovery
            </h1>
            <p className={styles.box2Para}>
              Get Account and asset access in case of device loss or forgot.
            </p>
          </div>
          {/* <div className={styles.box2}>
            <h1 className={styles.box2Heading}>Self Recovery</h1>
            <p className={styles.box2Para}>Get Account and asset access in case of device loss.</p>
          </div>
          <div className={styles.box2}>
            <h1 className={styles.box2Heading}>Self Recovery</h1>
            <p className={styles.box2Para}>Get Account and asset access in case of device loss.</p>
          </div> */}
          <div className={styles.box3}>
            <Image
              alt="green Pattern"
              src={greenpat}
              className={styles.logo_img}
            />
            <h1
              className={styles.box3Heading}
              style={{ marginBottom: "140px", marginTop: "-115px" }}
            >
              Multi Device
            </h1>
            <p className={styles.box3Para}>
              Get the flexibility to approve transactions from any of your
              devices.
            </p>
          </div>
          <div className={styles.box4}>
            <Image
              alt="blue Pattern"
              src={bluepat}
              className={styles.logo_img}
            />
            <h1
              className={styles.box4Heading}
              style={{ marginBottom: "140px", marginTop: "-115px" }}
            >
              Co-Own Assets
            </h1>
            <p className={styles.box4Para}>
              Own assets jointly without converting NFTs to fungible tokens
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}

{
  /* <div className={styles.box3}>
          <div className={styles.box3Text}>
            <h1>Multi Device</h1>
            <p>Get the flexibility to approve transactions from any of your devices.</p>
          </div>
        </div>
        <div className={styles.box4}>
          <div className={styles.box4Text}>
            <h1>Co-Own Assets</h1>
            <p>Own assets jointly without converting NFTs to fungible tokens</p>
          </div>
        </div> */
}
