import * as React from 'react'
import { useState } from 'react'
import Navbar from '@/components/Navbar/Navbar'
import Head from 'next/head'
import Footer from '@/components/Footer/Footer'
import styles from '@/styles/Myaccount.module.css'
import Image from 'next/image'
import createBtnLogo from '../assets/create-btn-logo.png'
import whiteHexaMesh from '../assets/white-hex-mesh.png'
import addressLogo from '../assets/address-logo1.png'
import etherLogo from '../assets/etherLogo.png'
import Box from '@mui/material/Box'
import Grid from '@mui/material/Grid'
import { addressFormatter, copyTextToClipboard } from '../utils/helper'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faCopy,
  faClock,
  faClockFour,
  faClockRotateLeft,
  faUserGroup,
  faCircleCheck,
  faCircleXmark,
  faSearch,
  faUserGear,
  faUserAlt,
  faUserAltSlash,
  faInfinity,
  faRotateRight,
} from '@fortawesome/free-solid-svg-icons'
import accountHoldingLogo from '../assets/account-holding.png'
import proposalHistoryLogo from '../assets/history-logo.png'
import transactionHistoryLogo from '../assets/transaction.png'
import manageAccountLogo from '../assets/manage.png'
import leftUpArrow from '../assets/leftuparrow.png'
import rightdowmArrow from '../assets/rightdownarrow.png'
import etheriumLogo from '../assets/etheriumlogo.png'
import Modal from '@mui/material/Modal'
import polygon from '../assets/polygon-logo.png'
import CreateAccount from '@/components/modals/CreateAccount'
import CreatePersonalAccount from '@/components/modals/CreatePersonalAccount'
import CreateTeamAccount from '@/components/modals/CreateTeamAccount'
import GenerateLink from '@/components/modals/GenerateLink'
import TransferAsset from '@/components/modals/TransferAsset'
import CreateProposal from '@/components/modals/CreateProposal'
import CreateProposalNon from '@/components/modals/CreateProposalNon'
import Confirmation from '@/components/modals/Confirmation'

import Link from 'next/link'

const style = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: '50%',
  bgcolor: '#1A1C20',
  border: '1px solid #ffffff',
  boxShadow: 24,
  p: 4,
  borderRadius: '10px',
}

function CreateProposalModal({ open, onClose }: any) {
  const [stage, setStage] = useState('1')
  const handleNextStage = (stage: any) => {
    setStage(stage)
  }
  return (
    <Modal
      open={open}
      onClose={() => {
        onClose()
        setStage('1')
      }}
      aria-labelledby="modal-modal-title"
      aria-describedby="modal-modal-description"
    >
      <Box sx={style} style={{ padding: '20px 50px' }}>
        {stage === '1' && <CreateProposal nextStage={handleNextStage} />}
      </Box>
    </Modal>
  )
}
function CreateProposalModalNon({ open, onClose }: any) {
  const [stage, setStage] = useState('1')
  const handleNextStage = (stage: any) => {
    setStage(stage)
  }
  return (
    <Modal
      open={open}
      onClose={() => {
        onClose()
        setStage('1')
      }}
      aria-labelledby="modal-modal-title"
      aria-describedby="modal-modal-description"
    >
      <Box sx={style} style={{ padding: '20px 50px' }}>
        {stage === '1' && <CreateProposalNon nextStage={handleNextStage} />}
      </Box>
    </Modal>
  )
}
function ConfirmationModal({ open, onClose }: any) {
  const [stage, setStage] = useState('1')
  const handleNextStage = (stage: any) => {
    setStage(stage)
  }
  return (
    <Modal
      open={open}
      onClose={() => {
        onClose()
        setStage('1')
      }}
      aria-labelledby="modal-modal-title"
      aria-describedby="modal-modal-description"
    >
      <Box sx={style} style={{ padding: '20px 50px' }}>
        {stage === '1' && <Confirmation nextStage={handleNextStage} />}
      </Box>
    </Modal>
  )
}

const Myaccount = () => {
  const [accountActiveOption, setAccountActiveOption] = React.useState(
    'account-holding',
  )
  const accountOPtionsHandler = (option: any) => {
    setAccountActiveOption(option)
  }
  const [open, setOpen] = React.useState(false)
  const handleOpen = () => setOpen(true)
  const handleClose = () => setOpen(false)

  return (
    <div style={{ background: '#404049' }}>
      <CreateProposalModal open={open} onClose={handleClose} />
      <Head>
        <title>Squad | My Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar navType={'secondary'} />
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            color: 'white',
            margin: '2rem',
            alignItems: 'flex-start',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <Image
              src={addressLogo}
              alt=""
              style={{
                height: '2.5rem',
                width: '2.5rem',
                marginRight: '7px',
              }}
            />
            <span
              style={{
                color: 'white',
                fontSize: '2rem',
                fontFamily: 'sans-serif !important',
              }}
            >
              My Account 1
            </span>
          </div>
          <Grid
            sm={12}
            style={{
              border: '2px solid white',
              borderRadius: '12px',
              padding: '1rem',
              marginTop: '1rem',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              width: '100%',
              fontFamily: 'sans-serif !important',
            }}
          >
            <Grid
              sm={3}
              style={
                accountActiveOption === 'account-holding'
                  ? {
                      textAlign: 'center',
                      border: '2px solid #1283FB',
                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: '#1283FB',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
                  : {
                      textAlign: 'center',
                      border: '2px solid #1283FB',
                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: 'rgba(19, 76, 136, 0.68)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
              }
              onClick={(e) => {
                accountOPtionsHandler('account-holding')
              }}
            >
              <Image src={accountHoldingLogo} alt="" />
              Account Holding
            </Grid>
            <Grid
              sm={3}
              style={
                accountActiveOption === 'proposal-history'
                  ? {
                      textAlign: 'center',
                      border: '2px solid #1283FB',
                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: '#1283FB',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
                  : {
                      textAlign: 'center',
                      border: '2px solid #1283FB',
                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: 'rgba(19, 76, 136, 0.68)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
              }
              onClick={() => {
                accountOPtionsHandler('proposal-history')
              }}
            >
              <Image src={proposalHistoryLogo} alt="" />
              Proposal History
            </Grid>
            <Grid
              sm={3}
              style={
                accountActiveOption === 'transaction-history'
                  ? {
                      textAlign: 'center',
                      border: '2px solid #1283FB',
                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: '#1283FB',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
                  : {
                      textAlign: 'center',
                      border: '2px solid #1283FB',
                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: 'rgba(19, 76, 136, 0.68)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
              }
              onClick={() => {
                accountOPtionsHandler('transaction-history')
              }}
            >
              <Image src={transactionHistoryLogo} alt="" />
              Transaction History
            </Grid>
            <Grid
              sm={3}
              style={
                accountActiveOption === 'manage-account'
                  ? {
                      textAlign: 'center',
                      border: '2px solid #1283FB',
                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: '#1283FB',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
                  : {
                      textAlign: 'center',
                      border: '2px solid #1283FB',

                      padding: '1rem',
                      margin: '5px',
                      width: '22%',
                      borderRadius: '10px',
                      background: 'rgba(19, 76, 136, 0.68)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '10px',
                      fontSize: '1.25rem',
                    }
              }
              onClick={() => {
                accountOPtionsHandler('manage-account')
              }}
            >
              <Image src={manageAccountLogo} alt="" />
              Manage Account
            </Grid>
          </Grid>
        </div>
        <div
          style={{
            // display: 'flex',
            border: '2px solid white',
            borderRadius: '4px',
            flexDirection: 'column',
            padding: '2rem',
            // alignItems: 'center',
            // justifyContent: 'space-between',
            // color: 'white',
            margin: '2rem',
            // alignItems: 'flex-start',
            fontFamily: 'sans-serif !important',
          }}
        >
          {accountActiveOption === 'account-holding' && <AccountHoldings />}
          {accountActiveOption === 'proposal-history' && <ProposalHistory />}
          {accountActiveOption === 'transaction-history' && (
            <TransactionHistory />
          )}
          {accountActiveOption === 'manage-account' && <ManageAccount />}
        </div>
      </main>
    </div>
  )
}

const AccountHoldings = () => {
  let activeSquads = [
    {
      assetsLogo: etherLogo,
      assets: '0.2864',
      purchasedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      time: '06/21/2021 21:00 GMT',
    },
    {
      assetsLogo: etherLogo,
      assets: '10.64',
      purchasedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      time: '06/21/2021 21:00 GMT',
    },
    {
      assetsLogo: etherLogo,
      assets: '0.7864',
      purchasedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      time: '06/21/2021 21:00 GMT',
    },
    {
      assetsLogo: etherLogo,
      assets: '0.2864',
      purchasedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      time: '06/21/2021 21:00 GMT',
    },
    {
      assetsLogo: etherLogo,
      assets: '0.394',
      purchasedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      time: '06/21/2021 21:00 GMT',
    },
    {
      assetsLogo: etherLogo,
      assets: '0.2864',
      purchasedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      time: '06/21/2021 21:00 GMT',
    },
  ]
  const [open, setOpen] = React.useState(false)
  const handleOpen = () => setOpen(true)
  const handleClose = () => setOpen(false)

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        fontFamily: 'sans-serif !important',
      }}
    >
      <CreateProposalModal open={open} onClose={handleClose} />
      {activeSquads ? (
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            // border: '2px solid #FF4E4E',
            width: '100%',
            margin: '15px',
          }}
        >
          <Grid
            container
            spacing={1}
            style={{
              marginBottom: '0.8rem',
              width: '100%',
              padding: '0.5rem',
              marginLeft: '0.099rem',
              borderRadius: '5px',
            }}
          >
            <Grid xs={3} style={{ display: 'flex', alignItems: 'center' }}>
              Assets
            </Grid>
            <Grid xs={3}>Purchased By</Grid>
            <Grid xs={3}>Timestamp</Grid>
            <Grid xs={3}>Actions</Grid>
          </Grid>
          {activeSquads.map(
            ({ assetsLogo, assets, purchasedBy, time }, index) => (
              <Grid
                key={`${time}-${index}`}
                container
                spacing={1}
                style={{
                  background: '#2F343F',
                  marginBottom: '0.8rem',
                  width: '100%',
                  padding: '0.5rem',
                  marginLeft: '0.099rem',
                  borderRadius: '5px',
                }}
              >
                <Grid xs={3} style={{ display: 'flex', alignItems: 'center' }}>
                  <Image
                    src={assetsLogo}
                    alt=""
                    style={{
                      height: '2rem',
                      width: 'auto',
                      marginRight: '0.5rem',
                    }}
                  />
                  <span>{assets}</span>
                </Grid>
                <Grid xs={3}>
                  <span style={{ marginRight: '0.5rem' }}>
                    {addressFormatter(purchasedBy)}
                  </span>
                  <FontAwesomeIcon
                    icon={faCopy}
                    style={{
                      fontSize: 18,
                      color: 'white',
                      fill: 'none',
                      fillOpacity: '1',

                      // fontWeight: '300',
                    }}
                    onClick={async () => {
                      await copyTextToClipboard(purchasedBy)
                      alert('Copied to clipboard')
                    }}
                  />
                </Grid>
                <Grid xs={3}>{time}</Grid>
                <Grid xs={3}>
                  {' '}
                  <button
                    style={{
                      background: '#1283FB',
                      borderRadius: '12px',
                      border: 'transparent',
                      width: '90px',
                      height: '30px',
                      color: '#fff',
                      marginRight: '1rem',
                    }}
                  >
                    Sell
                  </button>
                  <button
                    onClick={handleOpen}
                    style={{
                      background: '#1283FB',
                      borderRadius: '12px',
                      border: 'transparent',
                      width: '90px',
                      height: '30px',
                      color: '#fff',
                    }}
                  >
                    Transfer
                  </button>
                </Grid>
              </Grid>
            ),
          )}
        </div>
      ) : (
        <div
          style={{
            alignSelf: 'flex-end',
            marginBottom: '1rem',
          }}
        >
          There are no active squads. Click on create squad to create your own
          squad.
        </div>
      )}
    </div>
  )
}
const ProposalHistory = () => {
  let proposalHistory = [
    {
      proposalName: 'Hello ramu chaha',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Send',
      ammount: '1.245',
      status: 'Approved',
    },
    {
      proposalName: 'nft el leooo',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      ammount: '1.245',
      status: 'Rejected',
    },
    {
      proposalName: 'lamf dand gol bandhs',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Send',
      ammount: '1.245',
      status: 'Approved',
    },
  ]
  return (
    <div>
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'flex-start',
        }}
      >
        <FontAwesomeIcon
          icon={faClockRotateLeft}
          style={{
            fontSize: 25,
            color: '#1283FB',
            marginRight: '0.5rem',
          }}
        />
        <span style={{ fontSize: '1.25rem' }}>Past Proposals</span>
      </div>
      <div
        style={{
          border: '2px solid white',
          margin: '1rem 2rem',
          borderRadius: '5px',
          padding: '1rem',
        }}
      >
        <Grid container sm={12}>
          <Grid sm={3}>Proposal Name</Grid>
          <Grid sm={3}>Raised by</Grid>
          <Grid sm={2}>Type</Grid>
          <Grid sm={2}>Ammount</Grid>
          <Grid sm={2}>Status</Grid>
        </Grid>
        {proposalHistory.map(
          ({ proposalName, raisedBy, type, ammount, status }, index) => (
            <Grid
              key={`${raisedBy}-${index}`}
              container
              sm={12}
              style={{
                borderRadius: '5px',
                padding: '1rem',
                marginTop: '0.5rem',
                background: '#2F343F',
              }}
            >
              <Grid sm={3}>{proposalName}</Grid>
              <Grid sm={3}>
                <span style={{ marginRight: '0.5rem' }}>
                  {addressFormatter(raisedBy)}
                </span>
                <FontAwesomeIcon
                  icon={faCopy}
                  style={{
                    fontSize: 18,
                    color: 'white',
                    fill: 'none',
                    fillOpacity: '1',

                    // fontWeight: '300',
                  }}
                  onClick={async () => {
                    await copyTextToClipboard(raisedBy)
                    alert('Copied to clipboard')
                  }}
                />
              </Grid>
              <Grid
                sm={2}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'flex-start',
                }}
              >
                <Image
                  src={type === 'Buy' ? rightdowmArrow : leftUpArrow}
                  style={{
                    height: '1rem',
                    width: '1rem',
                    marginRight: '0.5rem',
                  }}
                  alt=""
                />
                <span>{type}</span>
              </Grid>
              <Grid sm={2} style={{ display: 'flex', alignItems: 'center' }}>
                <Image
                  src={etheriumLogo}
                  style={{
                    height: '1.5rem',
                    width: '1.5rem',
                    marginRight: '0.5rem',
                  }}
                  alt=""
                />

                <span>{ammount}</span>
              </Grid>

              <Grid sm={2}>
                <button
                  style={
                    status === 'Approved'
                      ? {
                          background: '#00FF0A',
                          border: 'none',
                          borderRadius: '1rem',
                          padding: '0.25rem 0',
                          width: '60%',
                          fontSize: '1.25rem',
                          color: 'white',
                        }
                      : {
                          background: '#FF4E4E',
                          border: 'none',
                          borderRadius: '1rem',
                          padding: '0.25rem 0',
                          width: '60%',
                          fontSize: '1.25rem',
                          color: 'white',
                        }
                  }
                >
                  {status}
                </button>
              </Grid>
            </Grid>
          ),
        )}
      </div>
    </div>
  )
}
const TransactionHistory = () => {
  let pendingTransaction = [
    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Send',
      timestamp: '06/21/2021 21:00 GMT',
    },
    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Send',
      timestamp: '06/21/2021 21:00 GMT',
    },
    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },
    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },

    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },

    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },

    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },

    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },

    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },

    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
    },
  ]
  let pastTransaction = [
    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
      ammount: '0.2864',
    },
    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Buy',
      timestamp: '06/21/2021 21:00 GMT',
      ammount: '0.2864',
    },
    {
      id: '0xc62a14212574393c6ac0ccfb627eca543178ae1602303137edf4d3081782bc4f',
      raisedBy: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111',
      type: 'Send',
      timestamp: '06/21/2021 21:00 GMT',
      ammount: '0.2864',
    },
  ]
  const [open, setOpen] = React.useState(false)
  const handleOpen = () => setOpen(true)
  const handleClose = () => setOpen(false)
  return (
    <div style={{ width: '100%' }}>
      <CreateProposalModalNon open={open} onClose={handleClose} />
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-start',
            alignSelf: 'flex-start',
          }}
        >
          <FontAwesomeIcon
            icon={faClockFour}
            style={{
              fontSize: 25,
              color: '#1283FB',
              marginRight: '0.5rem',
            }}
          />
          <span style={{ fontSize: '1.25rem' }}>Pending Transactions</span>
        </div>
        <div
          className={styles.box1}
          style={{
            border: '2px solid white',
            margin: '1rem 2rem',
            borderRadius: '5px',
            padding: '1rem',
          }}
        >
          <Grid container sm={12}>
            <Grid sm={2}>Transaction ID</Grid>
            <Grid sm={2}>Raised by</Grid>
            <Grid sm={2}>Type</Grid>
            <Grid sm={3}>Timestamp</Grid>
            <Grid sm={3}>Action</Grid>
          </Grid>
          {pendingTransaction.map(
            ({ id, raisedBy, timestamp, type }, index) => (
              <Grid
                key={`${raisedBy}-${index}`}
                container
                sm={12}
                style={{
                  borderRadius: '5px',
                  padding: '1rem',
                  marginTop: '0.5rem',
                  background: '#2F343F',
                }}
              >
                <Grid sm={2}>
                  <span style={{ marginRight: '0.5rem' }}>
                    {addressFormatter(id)}
                  </span>
                  <FontAwesomeIcon
                    icon={faCopy}
                    style={{
                      fontSize: 18,
                      color: 'white',
                      fill: 'none',
                      fillOpacity: '1',

                      // fontWeight: '300',
                    }}
                    onClick={async () => {
                      await copyTextToClipboard(id)
                      alert('Copied to clipboard')
                    }}
                  />
                </Grid>
                <Grid sm={2}>
                  <span style={{ marginRight: '0.5rem' }}>
                    {addressFormatter(raisedBy)}
                  </span>
                  <FontAwesomeIcon
                    icon={faCopy}
                    style={{
                      fontSize: 18,
                      color: 'white',
                      fill: 'none',
                      fillOpacity: '1',

                      // fontWeight: '300',
                    }}
                    onClick={async () => {
                      await copyTextToClipboard(raisedBy)
                      alert('Copied to clipboard')
                    }}
                  />
                </Grid>
                <Grid
                  sm={2}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'flex-start',
                  }}
                >
                  <Image
                    src={type === 'Buy' ? rightdowmArrow : leftUpArrow}
                    style={{
                      height: '1rem',
                      width: '1rem',
                      marginRight: '0.5rem',
                    }}
                    alt=""
                  />
                  <span>{type}</span>
                </Grid>
                <Grid sm={3}>{timestamp}</Grid>
                <Grid
                  sm={3}
                  style={{ textDecoration: 'underline', color: '#1283FB' }}
                  onClick={handleOpen}
                >
                  Create Proposal
                </Grid>
              </Grid>
            ),
          )}
        </div>
      </div>
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-start',
            alignSelf: 'flex-start',
          }}
        >
          <FontAwesomeIcon
            icon={faClockRotateLeft}
            style={{
              fontSize: 25,
              color: '#1283FB',
              marginRight: '0.5rem',
            }}
          />
          <span style={{ fontSize: '1.25rem' }}>Past Transactions</span>
        </div>
        <div
          className={styles.box1}
          style={{
            border: '2px solid white',
            margin: '1rem 2rem',
            borderRadius: '5px',
            padding: '1rem',
          }}
        >
          <Grid container sm={12}>
            <Grid sm={2}>Transaction ID</Grid>
            <Grid sm={2}>Raised by</Grid>
            <Grid sm={2}>Type</Grid>
            <Grid sm={3}>Timestamp</Grid>
            <Grid sm={3}>Ammount</Grid>
          </Grid>
          {pastTransaction.map(
            ({ id, raisedBy, timestamp, type, ammount }, index) => (
              <Grid
                key={`${raisedBy}-${index}`}
                container
                sm={12}
                style={{
                  borderRadius: '5px',
                  padding: '1rem',
                  marginTop: '0.5rem',
                  background: '#2F343F',
                }}
              >
                <Grid sm={2}>
                  <span style={{ marginRight: '0.5rem' }}>
                    {addressFormatter(id)}
                  </span>
                  <FontAwesomeIcon
                    icon={faCopy}
                    style={{
                      fontSize: 18,
                      color: 'white',
                      fill: 'none',
                      fillOpacity: '1',

                      // fontWeight: '300',
                    }}
                    onClick={async () => {
                      await copyTextToClipboard(id)
                      alert('Copied to clipboard')
                    }}
                  />
                </Grid>
                <Grid sm={2}>
                  <span style={{ marginRight: '0.5rem' }}>
                    {addressFormatter(raisedBy)}
                  </span>

                  <FontAwesomeIcon
                    icon={faCopy}
                    style={{
                      fontSize: 18,
                      color: 'white',
                      fill: 'none',
                      fillOpacity: '1',

                      // fontWeight: '300',
                    }}
                    onClick={async () => {
                      await copyTextToClipboard(raisedBy)
                      alert('Copied to clipboard')
                    }}
                  />
                </Grid>
                <Grid
                  sm={2}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'flex-start',
                  }}
                >
                  <Image
                    src={type === 'Buy' ? rightdowmArrow : leftUpArrow}
                    style={{
                      height: '1rem',
                      width: '1rem',
                      marginRight: '0.5rem',
                    }}
                    alt=""
                  />
                  <span>{type}</span>
                </Grid>
                <Grid sm={3}>{timestamp}</Grid>
                <Grid
                  sm={3}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'flex-start',
                  }}
                >
                  <Image
                    src={etheriumLogo}
                    style={{
                      height: '1.5rem',
                      width: '1.5rem',
                      marginRight: '0.5rem',
                    }}
                    alt=""
                  />
                  <span>{ammount}</span>
                </Grid>
              </Grid>
            ),
          )}
        </div>
      </div>
    </div>
  )
}
const ManageAccount = () => {
  let userRequest = [
    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },
    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },
    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },
    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },

    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },

    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },

    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },

    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },

    { address: '0x97fcb4e081Bb4fE8276FD4Fb24FBC9D778380111' },
  ]
  const [open, setOpen] = React.useState(false)
  const handleOpen = () => setOpen(true)
  const handleClose = () => setOpen(false)

  return (
    <div style={{ width: '100%' }}>
      <ConfirmationModal open={open} onClose={handleClose} />
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-start',
            alignSelf: 'flex-start',
          }}
        >
          <FontAwesomeIcon
            icon={faUserGroup}
            style={{
              fontSize: 25,
              color: '#1283FB',
              marginRight: '0.5rem',
            }}
          />
          <span style={{ fontSize: '1.25rem' }}>Membership Request</span>
        </div>
        <div
          className={styles.box1}
          style={{
            border: '2px solid white',
            margin: '1rem 2rem',
            borderRadius: '5px',
            padding: '1rem',
          }}
        >
          {userRequest.map(({ address }, index) => (
            <Grid
              key={`${address}-${index}`}
              container
              sm={12}
              style={{
                borderRadius: '5px',
                padding: '1rem',
                marginTop: '0.5rem',
                background: '#2F343F',
              }}
            >
              <Grid sm={2}>#{index}</Grid>
              <Grid sm={6}>
                <span style={{ marginRight: '0.5rem' }}>
                  {addressFormatter(address)}
                </span>
                <FontAwesomeIcon
                  icon={faCopy}
                  style={{
                    fontSize: 18,
                    color: 'white',
                    fill: 'none',
                    fillOpacity: '1',

                    // fontWeight: '300',
                  }}
                  onClick={async () => {
                    await copyTextToClipboard(address)
                    alert('Copied to clipboard')
                  }}
                />
              </Grid>
              <Grid
                sm={4}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-around',
                }}
              >
                <button
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#00FF0A',
                    fontSize: '1rem',
                    fontWeight: '600',
                    marginRight: '4rem',
                  }}
                  onClick={handleOpen}
                >
                  <FontAwesomeIcon
                    icon={faCircleCheck}
                    style={{
                      fontSize: 18,
                      color: '#00FF0A',
                      marginRight: '0.5rem',
                    }}
                  />
                  Accept
                </button>
                <button
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#FF4E4E',
                    fontSize: '1rem',
                    fontWeight: '600',
                  }}
                  onClick={handleOpen}
                >
                  <FontAwesomeIcon
                    icon={faCircleXmark}
                    style={{
                      fontSize: 18,
                      color: '#FF4E4E',
                      marginRight: '0.5rem',
                    }}
                  />
                  Decline
                </button>
              </Grid>
            </Grid>
          ))}
        </div>
      </div>

      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-start',
            alignSelf: 'flex-start',
          }}
        >
          <FontAwesomeIcon
            icon={faUserGroup}
            style={{
              fontSize: 25,
              color: '#1283FB',
              marginRight: '0.5rem',
            }}
          />
          <span style={{ fontSize: '1.25rem' }}>Manage Team Members</span>
        </div>
        <div
          className={styles.box1}
          style={{
            border: '2px solid white',
            margin: '1rem 2rem',
            borderRadius: '5px',
          }}
        >
          <div
            style={{
              background: '#2F343F',
              marginBottom: '1rem',
              border: '1px solid white',
              padding: '0.2rem 0.5rem',
              borderRadius: '12px',
              display: 'flex',
              alignItems: 'center',
              width: 'fit-content',
            }}
          >
            <FontAwesomeIcon
              icon={faSearch}
              style={{
                fontSize: 18,
                color: 'grey',
              }}
            />
            <input
              type="search"
              name=""
              id=""
              style={{
                background: '#2F343F',
                border: 'none',
                margin: '0',
                padding: '0.5rem',
                outline: 'none',
              }}
              placeholder="Search Team Member"
            />
          </div>

          {userRequest.map(({ address }, index) => (
            <Grid
              key={`${address}-${index}`}
              container
              sm={12}
              style={{
                borderRadius: '5px',
                padding: '1rem',
                marginTop: '0.5rem',
                background: '#2F343F',
              }}
            >
              <Grid sm={2}>#{index}</Grid>
              <Grid sm={6}>
                <span style={{ marginRight: '0.5rem' }}>
                  {addressFormatter(address)}
                </span>
                <FontAwesomeIcon
                  icon={faCopy}
                  style={{
                    fontSize: 18,
                    color: 'white',
                    fill: 'none',
                    fillOpacity: '1',
                  }}
                  onClick={async () => {
                    await copyTextToClipboard(address)
                    alert('Copied to clipboard')
                  }}
                />
              </Grid>
              <Grid
                sm={4}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-around',
                }}
              >
                <button
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#00FF0A',
                    fontSize: '1rem',
                    fontWeight: '600',
                    marginRight: '4rem',
                  }}
                  onClick={handleOpen}
                >
                  <FontAwesomeIcon
                    icon={faUserGear}
                    style={{
                      fontSize: 18,
                      color: '#00FF0A',
                      marginRight: '0.5rem',
                    }}
                  />
                  Manange Role
                </button>
                <button
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#FF4E4E',
                    fontSize: '1rem',
                    fontWeight: '600',
                  }}
                  onClick={handleOpen}
                >
                  <FontAwesomeIcon
                    icon={faUserAltSlash}
                    style={{
                      fontSize: 18,
                      color: '#FF4E4E',
                      marginRight: '0.5rem',
                    }}
                  />
                  Remove
                </button>
              </Grid>
            </Grid>
          ))}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              marginTop: '1rem',
            }}
          >
            <div style={{ flex: '1' }}>
              <div style={{ color: 'magenta', marginBottom: '0.4rem' }}>
                {' '}
                + Add More
              </div>
              <input
                type="text"
                name=""
                id=""
                placeholder="Invite via public key"
                style={{
                  width: '90%',
                  marginBottom: '0.4rem',
                  padding: '0.3rem 0.5rem',
                  borderRadius: '0.3rem',
                  background: '#2F343F',
                  border: '1px solid white',
                }}
              />
              <div style={{ fontSize: '0.9rem', color: '#1283FB' }}>
                {' '}
                Add multiple public keys separated by comma.
              </div>
            </div>

            <div
              style={{
                flex: '1',
                border: '1px solid white',
                borderRadius: '0.3rem',
                padding: '0.3rem 0.5rem',
                background: '#2F343F',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              <select
                name="invitelink"
                id="invitelink"
                style={{
                  background: 'none',
                  border: 'none',
                  color: 'white',
                  borderRight: 'none',
                }}
              >
                <option value="single">Single Use</option>
                <option value="mutli">Multi Use </option>
              </select>
              |
              <a
                style={{ width: '75%', color: '#89B0EE', paddingLeft: '1rem' }}
                href="htttps://sfsfsfsf.sfsfsfsfsfsf/fsfsf/fsfs"
              >
                htttps://sfsfsfsf.sfsfsfsfsfsf/fsfsf/fsfs
              </a>
              <div>
                <FontAwesomeIcon
                  icon={faCopy}
                  style={{
                    fontSize: 18,
                    color: 'white',
                    fill: 'none',
                    fillOpacity: '1',
                    marginRight: '0.5rem',

                    // fontWeight: '300',
                  }}
                  onClick={async () => {
                    await copyTextToClipboard('https://fafafafaafaf/fsfs')
                    alert('Copied to clipboard')
                  }}
                />

                <FontAwesomeIcon
                  icon={faRotateRight}
                  style={{
                    fontSize: 18,
                    color: 'white',
                    fill: 'none',
                    fillOpacity: '1',

                    // fontWeight: '300',
                  }}
                  onClick={async () => {
                    alert('Reaload')
                  }}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        style={{
          display: 'flex',
          alignItems: 'flex-start',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-start',
            alignSelf: 'flex-start',
          }}
        >
          <FontAwesomeIcon
            icon={faUserGroup}
            style={{
              fontSize: 25,
              color: '#1283FB',
              marginRight: '0.5rem',
            }}
          />
          <span style={{ fontSize: '1.25rem', margin: '15px 0 0 0' }}>
            Team Account Settings
          </span>
        </div>
        <div style={{ margin: '40px' }}>
          <label
            htmlFor="cars"
            className="form_lable"
            style={{ justifyContent: 'inherit', gap: '0.5rem' }}
          >
            <p className="form_text">Who can join?</p>
            <div>
              <div>
                <input type="radio" id="join" name="join" checked={true} />
                <label htmlFor="contactChoice1" className="form_text">
                  Anyone with the link
                </label>
              </div>
              <div>
                <input type="radio" id="join" name="join" />
                <label htmlFor="contactChoice2" className="form_text">
                  Add public key
                </label>
              </div>
            </div>
          </label>
          <label
            htmlFor="cars"
            className="form_lable"
            style={{ justifyContent: 'inherit', gap: '2rem' }}
          >
            <p className="form_text">Joining fee</p>
            <div>
              <div>
                <input
                  type="radio"
                  id="joinfees"
                  name="joinfees"
                  checked={true}
                />
                <label htmlFor="contactChoice1" className="form_text">
                  Free
                </label>
              </div>
              <div>
                <input type="radio" id="joinfees" name="joinfees" />
                <label htmlFor="contactChoice2" className="form_text">
                  <div
                    style={{
                      flex: '1',
                      border: '1px solid white',
                      borderRadius: '0.3rem',
                      padding: '0.2rem 0.3rem',
                      background: '#2F343F',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                    }}
                  >
                    <select
                      name="invitelink"
                      id="invitelink"
                      style={{
                        background: 'none',
                        border: 'none',
                        color: 'white',
                        borderRight: 'none',
                      }}
                    >
                      <option value="single">
                        <FontAwesomeIcon icon={faInfinity} />
                      </option>
                    </select>
                    |
                    <p
                      style={{
                        width: '75%',
                        paddingLeft: '0.5rem',
                        margin: '0',
                      }}
                    >
                      0.02548
                    </p>
                  </div>
                </label>
              </div>
            </div>
          </label>
          <label
            htmlFor="cars"
            className="form_lable"
            style={{ justifyContent: 'inherit' }}
          >
            <p className="form_text">Who pays gas?</p>
            <div>
              <div>
                <input type="radio" id="payGas" name="payGas" checked={true} />
                <label htmlFor="contactChoice1" className="form_text">
                  Deduct from team account
                </label>
              </div>
              <div>
                <input type="radio" id="payGas" name="payGas" />
                <label htmlFor="contactChoice2" className="form_text">
                  Dapp
                </label>
              </div>
            </div>
          </label>
          <label
            htmlFor="cars"
            className="form_lable"
            style={{ justifyContent: 'inherit', gap: '1.5rem' }}
          >
            <p className="form_text">Proposal fee</p>
            <div style={{ display: 'flex', flexDirection: 'row' }}>
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <div>
                  <input
                    type="radio"
                    id="propfee"
                    name="propfee"
                    checked={true}
                  />
                  <label htmlFor="contactChoice1" className="form_text">
                    Free
                  </label>
                </div>
                <div>
                  <input type="radio" id="propfee" name="payGas" />
                  <label htmlFor="contactChoice2" className="form_text">
                    <div
                      style={{
                        flex: '1',
                        border: '1px solid white',
                        borderRadius: '0.3rem',
                        padding: '0.2rem 0.3rem',
                        background: '#2F343F',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                      }}
                    >
                      <select
                        name="invitelink"
                        id="invitelink"
                        style={{
                          background: 'none',
                          border: 'none',
                          color: 'white',
                          borderRight: 'none',
                        }}
                      >
                        <option value="single">
                          <FontAwesomeIcon icon={faInfinity} />
                        </option>
                      </select>
                      |
                      <p
                        style={{
                          width: '75%',
                          paddingLeft: '0.5rem',
                          margin: '0',
                        }}
                      >
                        0.02548
                      </p>
                    </div>
                  </label>
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <div>
                  <input type="radio" id="addprop" name="addprop" />
                  <label htmlFor="contactChoice2" className="form_text">
                    Deduct from team account
                  </label>
                </div>
                <div>
                  <input type="radio" id="addprop" name="addprop" />
                  <label htmlFor="contactChoice2" className="form_text">
                    Initiator pays
                  </label>
                </div>
              </div>
            </div>
          </label>
          <div
            className="form_lable"
            style={{ justifyContent: 'inherit', gap: '1rem' }}
          >
            <p className="form_text" style={{ width: '124px' }}>
              {' '}
              Max Members
            </p>
            <input type="text" name="team_name" className="form_input" />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Myaccount
